export const paths = {
  dashboard: '/dashboard',
  activities: '/activities',
  activityNew: '/activities/new',
  activityDetail: '/activities/:id',
  evidences: '/evidences',
  approval: '/approval',
  reports: '/reports',
  reportBuilder: '/report-builder',
  units: '/units',
  settings: '/settings',
  archive: '/archive',
  calendar: '/calendar',
  featured: '/featured',
} as const;
