export interface DatabaseFieldDesign {
  ten_truong: string;
  kieu_du_lieu: string;
  mo_ta: string;
  ghi_chu: string;
}

export interface DatabaseCollectionDesign {
  ma_collection: string;
  ten_collection: string;
  muc_dich: string;
  truong: DatabaseFieldDesign[];
}

const f = (ten_truong: string, kieu_du_lieu: string, mo_ta: string, ghi_chu = ''): DatabaseFieldDesign => ({
  ten_truong,
  kieu_du_lieu,
  mo_ta,
  ghi_chu,
});

export const DATABASE_COLLECTION_DESIGNS: DatabaseCollectionDesign[] = [
  {
    ma_collection: 'nguoi_dung',
    ten_collection: 'nguoi_dung',
    muc_dich: 'Lưu hồ sơ người dùng nội bộ, liên kết với Firebase Auth qua uid.',
    truong: [
      f('uid', 'string', 'Khóa chính, trùng với Firebase Auth UID', 'Bắt buộc'),
      f('ho_ten', 'string', 'Họ và tên người dùng', 'Bắt buộc'),
      f('email', 'string', 'Email đăng nhập nội bộ', 'Bắt buộc, duy nhất'),
      f('ten_dang_nhap', 'string', 'Tên đăng nhập hiển thị/tra cứu', 'Tùy chọn'),
      f('ma_don_vi', 'string', 'Mã đơn vị trực thuộc', 'FK -> don_vi'),
      f('ten_don_vi', 'string', 'Tên đơn vị được copy để hiển thị nhanh', 'Denormalized'),
      f('ma_vai_tro', 'string', 'Vai trò của người dùng', 'FK -> vai_tro'),
      f('ten_vai_tro', 'string', 'Tên vai trò hiển thị', 'Denormalized'),
      f('trang_thai', 'string', 'dang_hoat_dong, tam_khoa, cho_doi_mat_khau, ngung_su_dung', 'Bắt buộc'),
      f('bat_buoc_doi_mat_khau', 'boolean', 'Yêu cầu đổi mật khẩu lần đầu', 'Mặc định true'),
      f('lan_dang_nhap_cuoi', 'timestamp', 'Thời điểm đăng nhập gần nhất', 'Tùy chọn'),
      f('ngay_tao', 'timestamp', 'Ngày tạo hồ sơ', 'Tự động'),
      f('nguoi_tao', 'string', 'UID admin tạo tài khoản', 'FK -> nguoi_dung'),
      f('ngay_cap_nhat', 'timestamp', 'Ngày cập nhật gần nhất', 'Tự động'),
    ],
  },
  {
    ma_collection: 'vai_tro',
    ten_collection: 'vai_tro',
    muc_dich: 'Quản lý vai trò và danh sách quyền được cấp cho từng nhóm người dùng.',
    truong: [
      f('ma_vai_tro', 'string', 'Khóa chính: super_admin, admin_doan_hoi...', 'Bắt buộc'),
      f('ten_vai_tro', 'string', 'Tên vai trò hiển thị', 'Bắt buộc'),
      f('mo_ta', 'string', 'Mô tả phạm vi quyền hạn', 'Tùy chọn'),
      f('cap_do', 'number', 'Cấp độ quyền', 'Bắt buộc'),
      f('la_mac_dinh', 'boolean', 'Đánh dấu vai trò mặc định của hệ thống', 'Mặc định false'),
      f('trang_thai', 'string', 'dang_su_dung, ngung_su_dung', 'Bắt buộc'),
      f('danh_sach_quyen', 'array<string>', 'Danh sách mã quyền được cấp', 'Tham chiếu quyen'),
      f('ngay_tao', 'timestamp', 'Ngày tạo vai trò', 'Tự động'),
      f('ngay_cap_nhat', 'timestamp', 'Ngày cập nhật', 'Tự động'),
    ],
  },
  {
    ma_collection: 'quyen',
    ten_collection: 'quyen',
    muc_dich: 'Khai báo các quyền chức năng để gắn vào vai_tro.',
    truong: [
      f('ma_quyen', 'string', 'Khóa chính: them_hoat_dong, duyet_hoat_dong...', 'Bắt buộc'),
      f('ten_quyen', 'string', 'Tên quyền hiển thị', 'Bắt buộc'),
      f('nhom_quyen', 'string', 'hoat_dong, minh_chung, bao_cao, nguoi_dung, don_vi, he_thong, luu_tru', 'Bắt buộc'),
      f('mo_ta', 'string', 'Giải thích quyền', 'Tùy chọn'),
      f('la_quyen_nguy_hiem', 'boolean', 'Đánh dấu quyền xóa, cấu hình, phân quyền', 'Mặc định false'),
      f('trang_thai', 'string', 'dang_su_dung, ngung_su_dung', 'Bắt buộc'),
    ],
  },
  {
    ma_collection: 'don_vi',
    ten_collection: 'don_vi',
    muc_dich: 'Quản lý Đoàn khoa, Liên chi Hội, Chi đoàn, Chi hội, CLB, đội/nhóm.',
    truong: [
      f('ma_don_vi', 'string', 'Khóa chính: lch_cntt, chi_hoi_k2023...', 'Bắt buộc'),
      f('ten_don_vi', 'string', 'Tên đơn vị đầy đủ', 'Bắt buộc'),
      f('loai_don_vi', 'string', 'doan_khoa, lien_chi_hoi, chi_doan, chi_hoi, cau_lac_bo, doi_nhom', 'Bắt buộc'),
      f('ma_don_vi_cha', 'string', 'Đơn vị cấp trên', 'FK -> don_vi, tùy chọn'),
      f('ten_don_vi_cha', 'string', 'Tên đơn vị cấp trên để hiển thị nhanh', 'Denormalized'),
      f('nguoi_phu_trach', 'string', 'Tên người phụ trách', 'Tùy chọn'),
      f('email_lien_he', 'string', 'Email liên hệ', 'Tùy chọn'),
      f('so_dien_thoai', 'string', 'Số điện thoại liên hệ', 'Tùy chọn'),
      f('trang_thai', 'string', 'dang_hoat_dong, ngung_hoat_dong', 'Bắt buộc'),
      f('ngay_tao', 'timestamp', 'Ngày tạo', 'Tự động'),
      f('ngay_cap_nhat', 'timestamp', 'Ngày cập nhật', 'Tự động'),
    ],
  },
  {
    ma_collection: 'nam_hoc',
    ten_collection: 'nam_hoc',
    muc_dich: 'Quản lý năm học, khóa dữ liệu cũ và phục vụ lưu trữ offline.',
    truong: [
      f('ma_nam_hoc', 'string', 'Khóa chính, ví dụ 2025_2026', 'Bắt buộc'),
      f('ten_nam_hoc', 'string', 'Tên hiển thị, ví dụ 2025-2026', 'Bắt buộc'),
      f('ngay_bat_dau', 'date', 'Ngày bắt đầu năm học', 'Bắt buộc'),
      f('ngay_ket_thuc', 'date', 'Ngày kết thúc năm học', 'Bắt buộc'),
      f('trang_thai', 'string', 'dang_hoat_dong, da_khoa, cho_luu_tru, da_luu_tru_offline, da_xoa_du_lieu_online', 'Bắt buộc'),
      f('la_nam_hoc_hien_tai', 'boolean', 'Đánh dấu năm học mặc định', 'Chỉ nên có 1 năm true'),
      f('da_luu_tru', 'boolean', 'Đã tạo gói lưu trữ hay chưa', 'Mặc định false'),
      f('da_xoa_du_lieu_online', 'boolean', 'Đã xóa dữ liệu chi tiết khỏi Firestore', 'Mặc định false'),
      f('ngay_tao', 'timestamp', 'Ngày tạo', 'Tự động'),
    ],
  },
  {
    ma_collection: 'loai_hoat_dong',
    ten_collection: 'loai_hoat_dong',
    muc_dich: 'Cấu hình danh mục loại hoạt động để lọc, thống kê và hiển thị màu sắc.',
    truong: [
      f('ma_loai', 'string', 'Khóa chính: hoc_thuat, tinh_nguyen...', 'Bắt buộc'),
      f('ten_loai', 'string', 'Tên loại hoạt động', 'Bắt buộc'),
      f('mo_ta', 'string', 'Mô tả nội dung loại hoạt động', 'Tùy chọn'),
      f('mau_hien_thi', 'string', 'Mã màu HEX dùng trong UI', 'Tùy chọn'),
      f('icon', 'string', 'Tên icon lucide-react', 'Tùy chọn'),
      f('trang_thai', 'string', 'dang_su_dung, ngung_su_dung', 'Bắt buộc'),
      f('thu_tu', 'number', 'Thứ tự hiển thị', 'Tùy chọn'),
    ],
  },
  {
    ma_collection: 'hoat_dong',
    ten_collection: 'hoat_dong',
    muc_dich: 'Collection trung tâm lưu thông tin hoạt động Đoàn - Hội theo năm học, đơn vị và trạng thái duyệt.',
    truong: [
      f('ma_hoat_dong', 'string', 'Khóa chính: hd_2025_2026_001', 'Bắt buộc'),
      f('ten_hoat_dong', 'string', 'Tên hoạt động', 'Bắt buộc'),
      f('ma_nam_hoc', 'string', 'Năm học của hoạt động', 'FK -> nam_hoc'),
      f('ten_nam_hoc', 'string', 'Tên năm học để hiển thị/lọc nhanh', 'Denormalized'),
      f('ma_loai', 'string', 'Loại hoạt động', 'FK -> loai_hoat_dong'),
      f('ten_loai', 'string', 'Tên loại để hiển thị nhanh', 'Denormalized'),
      f('ma_don_vi', 'string', 'Đơn vị tổ chức', 'FK -> don_vi'),
      f('ten_don_vi', 'string', 'Tên đơn vị tổ chức', 'Denormalized'),
      f('cap_to_chuc', 'string', 'cap_chi_hoi, cap_chi_doan, cap_clb, cap_khoa, cap_truong, cap_thanh, cap_trung_uong', 'Bắt buộc'),
      f('thoi_gian_bat_dau', 'timestamp', 'Thời gian bắt đầu', 'Bắt buộc'),
      f('thoi_gian_ket_thuc', 'timestamp', 'Thời gian kết thúc', 'Tùy chọn'),
      f('dia_diem', 'string', 'Địa điểm tổ chức', 'Tùy chọn'),
      f('doi_tuong_tham_gia', 'string', 'Đối tượng tham gia', 'Tùy chọn'),
      f('so_luong_tham_gia', 'number', 'Tổng số lượt/sinh viên tham gia', 'Mặc định 0'),
      f('kinh_phi_hoat_dong', 'array<object>', 'Danh sách nguồn kinh phí và số tiền', 'Tùy chọn'),
      f('noi_dung', 'string', 'Nội dung triển khai', 'Tùy chọn'),
      f('ket_qua', 'string', 'Kết quả đạt được', 'Tùy chọn'),
      f('link_bai_viet', 'string', 'Link bài truyền thông Facebook/web', 'Tùy chọn'),
      f('link_thu_muc_minh_chung', 'string', 'Link folder Drive/R2', 'Tùy chọn'),
      f('anh_dai_dien', 'string', 'URL ảnh đại diện', 'Tùy chọn'),
      f('so_luong_minh_chung', 'number', 'Số minh chứng gắn với hoạt động', 'Tự động cập nhật'),
      f('trang_thai', 'string', 'ban_nhap, cho_duyet, da_duyet, can_bo_sung, tu_choi, da_luu_tru', 'Bắt buộc'),
      f('ly_do_yeu_cau_bo_sung', 'string', 'Nhận xét khi cần bổ sung', 'Tùy chọn'),
      f('nguoi_tao', 'string', 'UID người tạo', 'FK -> nguoi_dung'),
      f('ten_nguoi_tao', 'string', 'Tên người tạo', 'Denormalized'),
      f('nguoi_duyet', 'string', 'UID người duyệt', 'FK -> nguoi_dung, tùy chọn'),
      f('ten_nguoi_duyet', 'string', 'Tên người duyệt', 'Tùy chọn'),
      f('ngay_tao', 'timestamp', 'Ngày tạo', 'Tự động'),
      f('ngay_cap_nhat', 'timestamp', 'Ngày cập nhật', 'Tự động'),
      f('ngay_gui_duyet', 'timestamp', 'Ngày gửi duyệt', 'Tùy chọn'),
      f('ngay_duyet', 'timestamp', 'Ngày duyệt', 'Tùy chọn'),
      f('da_luu_tru', 'boolean', 'Đánh dấu thuộc gói archive', 'Mặc định false'),
      f('tu_khoa_tim_kiem', 'array<string>', 'Từ khóa phục vụ search', 'Tùy chọn'),
    ],
  },
  {
    ma_collection: 'minh_chung',
    ten_collection: 'minh_chung',
    muc_dich: 'Lưu metadata và đường dẫn file minh chứng; file thật nằm ở Google Drive/Cloudflare R2.',
    truong: [
      f('ma_minh_chung', 'string', 'Khóa chính', 'Bắt buộc'),
      f('ma_hoat_dong', 'string', 'Hoạt động liên quan', 'FK -> hoat_dong'),
      f('ten_hoat_dong', 'string', 'Tên hoạt động để hiển thị nhanh', 'Denormalized'),
      f('ten_minh_chung', 'string', 'Tên minh chứng', 'Bắt buộc'),
      f('loai_minh_chung', 'string', 'hinh_anh, video, file_ke_hoach, file_bao_cao, danh_sach_tham_gia, link_facebook, link_google_drive, bien_ban, giay_chung_nhan, cong_van, khac', 'Bắt buộc'),
      f('nguon_luu_tru', 'string', 'google_drive, cloudflare_r2, link_ngoai, firebase_storage', 'Bắt buộc'),
      f('ten_file', 'string', 'Tên file gốc', 'Tùy chọn'),
      f('duong_dan_file', 'string', 'URL file/link minh chứng', 'Bắt buộc'),
      f('duong_dan_thu_muc', 'string', 'URL folder chứa file', 'Tùy chọn'),
      f('dinh_dang_file', 'string', 'jpg, png, pdf, docx, xlsx...', 'Tùy chọn'),
      f('dung_luong_file', 'number', 'Dung lượng byte nếu có', 'Tùy chọn'),
      f('ma_nam_hoc', 'string', 'Năm học để lọc/xóa archive', 'FK -> nam_hoc'),
      f('ma_don_vi', 'string', 'Đơn vị sở hữu', 'FK -> don_vi'),
      f('nguoi_tai_len', 'string', 'UID người tải lên', 'FK -> nguoi_dung'),
      f('ten_nguoi_tai_len', 'string', 'Tên người tải lên', 'Denormalized'),
      f('trang_thai', 'string', 'dang_su_dung, da_xoa, da_luu_tru', 'Bắt buộc'),
      f('ngay_tai_len', 'timestamp', 'Ngày tải lên', 'Tự động'),
    ],
  },
  {
    ma_collection: 'duyet_hoat_dong',
    ten_collection: 'duyet_hoat_dong',
    muc_dich: 'Ghi lịch sử gửi duyệt, duyệt, từ chối, yêu cầu bổ sung của mỗi hoạt động.',
    truong: [
      f('ma_duyet', 'string', 'Khóa chính', 'Bắt buộc'),
      f('ma_hoat_dong', 'string', 'Hoạt động được xử lý', 'FK -> hoat_dong'),
      f('ten_hoat_dong', 'string', 'Tên hoạt động', 'Denormalized'),
      f('hanh_dong', 'string', 'gui_duyet, duyet, tu_choi, yeu_cau_bo_sung, cap_nhat_lai, khoa_hoat_dong', 'Bắt buộc'),
      f('trang_thai_truoc', 'string', 'Trạng thái trước khi xử lý', 'Bắt buộc'),
      f('trang_thai_sau', 'string', 'Trạng thái sau khi xử lý', 'Bắt buộc'),
      f('nhan_xet', 'string', 'Nhận xét của người duyệt', 'Tùy chọn'),
      f('nguoi_thuc_hien', 'string', 'UID người thực hiện', 'FK -> nguoi_dung'),
      f('ten_nguoi_thuc_hien', 'string', 'Tên người thực hiện', 'Denormalized'),
      f('ngay_thuc_hien', 'timestamp', 'Thời điểm thao tác', 'Tự động'),
    ],
  },
  {
    ma_collection: 'mau_bao_cao',
    ten_collection: 'mau_bao_cao',
    muc_dich: 'Cấu hình template báo cáo để module Tạo báo cáo sử dụng.',
    truong: [
      f('ma_mau', 'string', 'Khóa chính', 'Bắt buộc'),
      f('ten_mau', 'string', 'Tên mẫu báo cáo', 'Bắt buộc'),
      f('loai_bao_cao', 'string', 'ket_qua_hoat_dong, tong_ket_nam_hoc, thi_dua, minh_chung, sinh_vien_5_tot, tinh_nguyen, hoc_thuat, mo_hinh_giai_phap', 'Bắt buộc'),
      f('mo_ta', 'string', 'Mô tả mẫu', 'Tùy chọn'),
      f('don_vi_ap_dung', 'array<string>', 'Danh sách loại đơn vị được dùng', 'Tùy chọn'),
      f('cau_truc', 'array<object>', 'Các mục tiêu đề/nội dung mẫu', 'Bắt buộc'),
      f('truong_du_lieu_dong', 'array<string>', 'Danh sách biến động trong mẫu', 'Bắt buộc'),
      f('ho_tro_word', 'boolean', 'Cho phép xuất Word', 'Mặc định true'),
      f('ho_tro_pdf', 'boolean', 'Cho phép xuất PDF', 'Mặc định true'),
      f('ho_tro_excel', 'boolean', 'Cho phép xuất Excel', 'Mặc định false'),
      f('la_mac_dinh', 'boolean', 'Đặt làm mẫu mặc định cho loại báo cáo', 'Mặc định false'),
      f('trang_thai', 'string', 'dang_su_dung, ban_nhap, tam_khoa, ngung_su_dung', 'Bắt buộc'),
      f('nguoi_tao', 'string', 'UID người tạo', 'FK -> nguoi_dung'),
      f('ngay_tao', 'timestamp', 'Ngày tạo', 'Tự động'),
      f('ngay_cap_nhat', 'timestamp', 'Ngày cập nhật', 'Tự động'),
    ],
  },
  {
    ma_collection: 'bao_cao_da_tao',
    ten_collection: 'bao_cao_da_tao',
    muc_dich: 'Lưu lịch sử các file báo cáo đã xuất từ module Tạo báo cáo.',
    truong: [
      f('ma_bao_cao', 'string', 'Khóa chính', 'Bắt buộc'),
      f('ten_bao_cao', 'string', 'Tên báo cáo', 'Bắt buộc'),
      f('ma_mau', 'string', 'Mẫu báo cáo đã sử dụng', 'FK -> mau_bao_cao'),
      f('loai_bao_cao', 'string', 'Loại báo cáo', 'Bắt buộc'),
      f('ma_nam_hoc', 'string', 'Năm học được tổng hợp', 'FK -> nam_hoc'),
      f('ten_nam_hoc', 'string', 'Tên năm học', 'Denormalized'),
      f('ma_don_vi', 'string', 'Đơn vị báo cáo', 'FK -> don_vi'),
      f('ten_don_vi', 'string', 'Tên đơn vị', 'Denormalized'),
      f('bo_loc_su_dung', 'object', 'Năm học, học kỳ, loại hoạt động, trạng thái...', 'Bắt buộc'),
      f('dinh_dang', 'string', 'docx, pdf, xlsx', 'Bắt buộc'),
      f('duong_dan_file', 'string', 'URL file đã xuất', 'Bắt buộc'),
      f('nguon_luu_tru', 'string', 'google_drive, cloudflare_r2', 'Bắt buộc'),
      f('nguoi_tao', 'string', 'UID người tạo báo cáo', 'FK -> nguoi_dung'),
      f('ten_nguoi_tao', 'string', 'Tên người tạo', 'Denormalized'),
      f('ngay_tao', 'timestamp', 'Ngày tạo', 'Tự động'),
    ],
  },
  {
    ma_collection: 'luu_tru_nam_hoc',
    ten_collection: 'luu_tru_nam_hoc',
    muc_dich: 'Quản lý gói nén/tải về dữ liệu năm cũ để tiết kiệm dung lượng Firestore.',
    truong: [
      f('ma_luu_tru', 'string', 'Khóa chính: archive_2025_2026', 'Bắt buộc'),
      f('ma_nam_hoc', 'string', 'Năm học được lưu trữ', 'FK -> nam_hoc'),
      f('ten_nam_hoc', 'string', 'Tên năm học', 'Denormalized'),
      f('tong_hoat_dong', 'number', 'Tổng hoạt động trong năm', 'Thống kê'),
      f('tong_minh_chung', 'number', 'Tổng minh chứng', 'Thống kê'),
      f('tong_bao_cao', 'number', 'Tổng báo cáo đã tạo', 'Thống kê'),
      f('tong_dung_luong_uoc_tinh', 'number', 'Tổng dung lượng byte ước tính', 'Thống kê'),
      f('ten_file_luu_tru', 'string', 'Tên file zip', 'Tùy chọn'),
      f('duong_dan_file_luu_tru', 'string', 'URL file zip lưu trữ', 'Tùy chọn'),
      f('nguon_luu_tru', 'string', 'google_drive, cloudflare_r2', 'Bắt buộc'),
      f('trang_thai', 'string', 'chua_luu_tru, dang_tao_goi, da_tao_goi, da_tai_xuong, da_xac_nhan_sao_luu, da_luu_tru_offline, da_xoa_du_lieu_online', 'Bắt buộc'),
      f('da_xac_nhan_sao_luu', 'boolean', 'Admin đã xác nhận tải và kiểm tra gói lưu trữ', 'Mặc định false'),
      f('da_xoa_du_lieu_online', 'boolean', 'Đã xóa dữ liệu chi tiết trong Firestore', 'Mặc định false'),
      f('nguoi_tao_goi', 'string', 'UID người tạo gói', 'FK -> nguoi_dung'),
      f('ngay_tao_goi', 'timestamp', 'Ngày tạo gói', 'Tùy chọn'),
      f('nguoi_xoa_du_lieu', 'string', 'UID người xóa dữ liệu', 'FK -> nguoi_dung, tùy chọn'),
      f('ngay_xoa_du_lieu', 'timestamp', 'Ngày xóa dữ liệu', 'Tùy chọn'),
    ],
  },
  {
    ma_collection: 'nhat_ky_he_thong',
    ten_collection: 'nhat_ky_he_thong',
    muc_dich: 'Lưu audit log các thao tác quan trọng như xóa dữ liệu, khóa tài khoản, đổi quyền.',
    truong: [
      f('ma_nhat_ky', 'string', 'Khóa chính', 'Bắt buộc'),
      f('ma_nguoi_dung', 'string', 'UID người thao tác', 'FK -> nguoi_dung'),
      f('ten_nguoi_dung', 'string', 'Tên người thao tác', 'Denormalized'),
      f('hanh_dong', 'string', 'Tên hành động', 'Bắt buộc'),
      f('module', 'string', 'Module bị tác động', 'Bắt buộc'),
      f('ma_doi_tuong', 'string', 'ID đối tượng bị tác động', 'Tùy chọn'),
      f('noi_dung', 'string', 'Mô tả chi tiết', 'Bắt buộc'),
      f('muc_do', 'string', 'thong_tin, canh_bao, nguy_hiem', 'Bắt buộc'),
      f('dia_chi_ip', 'string', 'IP thực hiện nếu có', 'Tùy chọn'),
      f('thoi_gian', 'timestamp', 'Thời điểm ghi log', 'Tự động'),
    ],
  },
  {
    ma_collection: 'cai_dat_he_thong',
    ten_collection: 'cai_dat_he_thong',
    muc_dich: 'Lưu cấu hình chung của hệ thống, thường dùng document thong_tin_chung.',
    truong: [
      f('ten_he_thong', 'string', 'Tên hệ thống', 'Bắt buộc'),
      f('ten_don_vi', 'string', 'Tên đơn vị chủ quản', 'Bắt buộc'),
      f('logo_url', 'string', 'Đường dẫn logo', 'Tùy chọn'),
      f('email_lien_he', 'string', 'Email liên hệ', 'Tùy chọn'),
      f('mau_chu_dao', 'string', 'Màu chủ đạo HEX', 'Tùy chọn'),
      f('cho_phep_dang_ky', 'boolean', 'Cho phép user tự đăng ký hay không', 'Mặc định false'),
      f('cho_phep_google_login', 'boolean', 'Cho phép Google login hay không', 'Mặc định false'),
      f('chi_admin_tao_tai_khoan', 'boolean', 'Chỉ admin được tạo tài khoản', 'Mặc định true'),
      f('nam_hoc_hien_tai', 'string', 'Mã năm học hiện tại', 'FK -> nam_hoc'),
      f('ngay_cap_nhat', 'timestamp', 'Ngày cập nhật', 'Tự động'),
    ],
  },
  {
    ma_collection: 'thong_bao',
    ten_collection: 'thong_bao',
    muc_dich: 'Quản lý thông báo nội bộ về duyệt hoạt động, cần bổ sung minh chứng, báo cáo.',
    truong: [
      f('ma_thong_bao', 'string', 'Khóa chính', 'Bắt buộc'),
      f('tieu_de', 'string', 'Tiêu đề thông báo', 'Bắt buộc'),
      f('noi_dung', 'string', 'Nội dung thông báo', 'Bắt buộc'),
      f('loai_thong_bao', 'string', 'duyet_hoat_dong, bao_cao, he_thong, luu_tru', 'Bắt buộc'),
      f('ma_nguoi_nhan', 'string', 'UID người nhận', 'FK -> nguoi_dung'),
      f('da_doc', 'boolean', 'Trạng thái đã đọc', 'Mặc định false'),
      f('duong_dan', 'string', 'URL nội bộ đến đối tượng liên quan', 'Tùy chọn'),
      f('ngay_tao', 'timestamp', 'Ngày tạo', 'Tự động'),
    ],
  },
];

export const NORMALIZED_VALUE_GROUPS = [
  { nhom: 'trang_thai nguoi_dung', gia_tri: ['dang_hoat_dong', 'tam_khoa', 'cho_doi_mat_khau', 'ngung_su_dung'] },
  { nhom: 'ma_vai_tro', gia_tri: ['super_admin', 'admin_doan_hoi', 'ban_chap_hanh', 'can_bo_chi_doan_chi_hoi', 'cong_tac_vien', 'nguoi_xem'] },
  { nhom: 'nhom_quyen', gia_tri: ['hoat_dong', 'minh_chung', 'bao_cao', 'nguoi_dung', 'don_vi', 'he_thong', 'luu_tru'] },
  { nhom: 'loai_don_vi', gia_tri: ['doan_khoa', 'lien_chi_hoi', 'chi_doan', 'chi_hoi', 'cau_lac_bo', 'doi_nhom'] },
  { nhom: 'trang_thai nam_hoc', gia_tri: ['dang_hoat_dong', 'da_khoa', 'cho_luu_tru', 'da_tao_goi_luu_tru', 'da_luu_tru_offline', 'da_xoa_du_lieu_online'] },
  { nhom: 'trang_thai hoat_dong', gia_tri: ['ban_nhap', 'cho_duyet', 'da_duyet', 'can_bo_sung', 'tu_choi', 'da_luu_tru'] },
  { nhom: 'cap_to_chuc', gia_tri: ['cap_chi_hoi', 'cap_chi_doan', 'cap_clb', 'cap_khoa', 'cap_truong', 'cap_thanh', 'cap_trung_uong'] },
  { nhom: 'loai_minh_chung', gia_tri: ['hinh_anh', 'video', 'file_ke_hoach', 'file_bao_cao', 'danh_sach_tham_gia', 'link_facebook', 'link_google_drive', 'bien_ban', 'giay_chung_nhan', 'cong_van', 'khac'] },
  { nhom: 'nguon_luu_tru', gia_tri: ['google_drive', 'cloudflare_r2', 'link_ngoai', 'firebase_storage'] },
  { nhom: 'hanh_dong duyet_hoat_dong', gia_tri: ['gui_duyet', 'duyet', 'tu_choi', 'yeu_cau_bo_sung', 'cap_nhat_lai', 'khoa_hoat_dong'] },
  { nhom: 'loai_bao_cao', gia_tri: ['ket_qua_hoat_dong', 'tong_ket_nam_hoc', 'thi_dua', 'minh_chung', 'sinh_vien_5_tot', 'tinh_nguyen', 'hoc_thuat', 'mo_hinh_giai_phap'] },
];

export const DEFAULT_REPORT_TEMPLATES = [
  {
    ma_mau: 'ket_qua_hoat_dong',
    ten_mau: 'Báo cáo kết quả hoạt động',
    loai_bao_cao: 'ket_qua_hoat_dong',
    mo_ta: 'Mẫu báo cáo kết quả cho một hoặc nhiều hoạt động đã duyệt.',
    cau_truc: [
      { thu_tu: 1, tieu_de: 'Thông tin chung', kieu: 'section' },
      { thu_tu: 2, tieu_de: 'Nội dung triển khai', kieu: 'section' },
      { thu_tu: 3, tieu_de: 'Kết quả đạt được', kieu: 'section' },
      { thu_tu: 4, tieu_de: 'Minh chứng kèm theo', kieu: 'section' },
    ],
    truong_du_lieu_dong: ['ten_hoat_dong', 'ten_don_vi', 'ten_loai', 'thoi_gian_bat_dau', 'dia_diem', 'so_luong_tham_gia', 'ket_qua', 'link_thu_muc_minh_chung'],
  },
  {
    ma_mau: 'tong_ket_nam_hoc',
    ten_mau: 'Báo cáo tổng kết năm học',
    loai_bao_cao: 'tong_ket_nam_hoc',
    mo_ta: 'Mẫu tổng hợp số liệu hoạt động, minh chứng và báo cáo theo năm học.',
    cau_truc: [
      { thu_tu: 1, tieu_de: 'Tổng quan năm học', kieu: 'section' },
      { thu_tu: 2, tieu_de: 'Thống kê theo loại hoạt động', kieu: 'table' },
      { thu_tu: 3, tieu_de: 'Thống kê theo đơn vị', kieu: 'table' },
      { thu_tu: 4, tieu_de: 'Nhận xét và đề xuất', kieu: 'section' },
    ],
    truong_du_lieu_dong: ['ma_nam_hoc', 'ten_nam_hoc', 'tong_hoat_dong', 'tong_minh_chung', 'tong_nguoi_tham_gia', 'don_vi_noi_bat'],
  },
  {
    ma_mau: 'minh_chung',
    ten_mau: 'Danh mục minh chứng',
    loai_bao_cao: 'minh_chung',
    mo_ta: 'Mẫu liệt kê đường dẫn minh chứng theo hoạt động, đơn vị và năm học.',
    cau_truc: [
      { thu_tu: 1, tieu_de: 'Thông tin lọc minh chứng', kieu: 'section' },
      { thu_tu: 2, tieu_de: 'Danh sách minh chứng', kieu: 'table' },
    ],
    truong_du_lieu_dong: ['ten_minh_chung', 'ten_hoat_dong', 'loai_minh_chung', 'nguon_luu_tru', 'duong_dan_file', 'ngay_tai_len'],
  },
];
