export const PUBLIC_FEATURED_DATA = {
  heroActivity: {
    title: 'Ngày hội tình nguyện mùa hè xanh 2026',
    description:
      'Chương trình tình nguyện quy mô lớn với sự tham gia của hơn 500 sinh viên, mang đến nhiều hoạt động ý nghĩa cho cộng đồng và góp phần nâng cao tinh thần trách nhiệm xã hội của thế hệ trẻ.',
    image: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=1200&h=600&fit=crop',
    date: '20/06/2026',
    location: 'Hội trường A',
    participants: 520,
    category: 'Tình nguyện',
    unit: 'Đoàn CNTT',
  },
  featuredActivities: [
    {
      id: 1,
      title: 'Hội thảo khoa học sinh viên lần thứ 20',
      category: 'Học thuật',
      date: '25/05/2026',
      unit: 'Đoàn Khoa học',
      image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop',
    },
    {
      id: 2,
      title: 'Workshop về AI và Machine Learning',
      category: 'Học thuật',
      date: '15/05/2026',
      unit: 'Đoàn CNTT',
      image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400&h=300&fit=crop',
    },
    {
      id: 3,
      title: 'Chiến dịch Mùa hè xanh 2026',
      category: 'Tình nguyện',
      date: '10/06/2026',
      unit: 'Đoàn CNTT',
      image: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=400&h=300&fit=crop',
    },
    {
      id: 4,
      title: 'Sinh viên 5 tốt cấp trường 2026',
      category: 'SV5T',
      date: '28/04/2026',
      unit: 'Hội SVHS',
      image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400&h=300&fit=crop',
    },
    {
      id: 5,
      title: 'Talkshow kỹ năng giao tiếp và thuyết trình',
      category: 'Kỹ năng',
      date: '20/04/2026',
      unit: 'Hội SVHS',
      image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=300&fit=crop',
    },
    {
      id: 6,
      title: 'Giải bóng đá sinh viên cúp Đoàn trường',
      category: 'Văn hóa - Thể thao',
      date: '15/03/2026',
      unit: 'Hội SVHS',
      image: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=400&h=300&fit=crop',
    },
    {
      id: 7,
      title: 'Chương trình truyền thông chào tân sinh viên K67',
      category: 'Truyền thông',
      date: '03/09/2025',
      unit: 'Đoàn CNTT',
      image: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=400&h=300&fit=crop',
    },
    {
      id: 8,
      title: 'Hiến máu tình nguyện - Giọt hồng yêu thương',
      category: 'Tình nguyện',
      date: '08/05/2026',
      unit: 'Hội chữ thập đỏ',
      image: 'https://images.unsplash.com/photo-1615461066159-fea0960485d5?w=400&h=300&fit=crop',
    },
    {
      id: 9,
      title: 'Olympic Tin học sinh viên toàn quốc',
      category: 'Học thuật',
      date: '05/05/2026',
      unit: 'Đoàn CNTT',
      image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop',
    },
  ],
  stats: {
    title: 'Thành tích nổi bật năm học 2025-2026',
    items: [
      { label: 'Hoạt động tổ chức', value: '410' },
      { label: 'Lượt tham gia', value: '13,480' },
      { label: 'Đơn vị tham gia', value: '48' },
      { label: 'Hoạt động nổi bật', value: '25' },
    ],
  },
};

export const ACTIVITY_LIST_DISPLAY_DATA = [
  { id: 1, name: 'Ngày hội tình nguyện mùa hè xanh 2026', category: 'Tình nguyện', unit: 'Đoàn CNTT', date: '15/05/2026', participants: 450, evidence: 25, status: 'approved' },
  { id: 2, name: 'Hội thảo khoa học sinh viên lần thứ 20', category: 'Học thuật', unit: 'Đoàn Khoa học', date: '12/05/2026', participants: 320, evidence: 18, status: 'pending' },
  { id: 3, name: 'Chương trình đào tạo kỹ năng mềm K66', category: 'Kỹ năng', unit: 'Hội SVHS', date: '10/05/2026', participants: 280, evidence: 15, status: 'approved' },
  { id: 4, name: 'Hiến máu tình nguyện - Giọt hồng yêu thương', category: 'Tình nguyện', unit: 'Hội chữ thập đỏ', date: '08/05/2026', participants: 520, evidence: 30, status: 'approved' },
  { id: 5, name: 'Cuộc thi Olympic Tin học sinh viên', category: 'Học thuật', unit: 'Đoàn CNTT', date: '05/05/2026', participants: 180, evidence: 12, status: 'draft' },
  { id: 6, name: 'Chương trình truyền thông chào tân sinh viên K67', category: 'Truyền thông', unit: 'Đoàn CNTT', date: '03/05/2026', participants: 650, evidence: 40, status: 'need-update' },
  { id: 7, name: 'Workshop về AI và Machine Learning', category: 'Học thuật', unit: 'Đoàn CNTT', date: '01/05/2026', participants: 220, evidence: 10, status: 'approved' },
  { id: 8, name: 'Sinh viên 5 tốt cấp trường 2026', category: 'SV5T', unit: 'Hội SVHS', date: '28/04/2026', participants: 95, evidence: 50, status: 'pending' },
  { id: 9, name: 'Chiến dịch Mùa hè xanh 2026', category: 'Tình nguyện', unit: 'Đoàn CNTT', date: '25/04/2026', participants: 380, evidence: 22, status: 'approved' },
  { id: 10, name: 'Talkshow kỹ năng giao tiếp và thuyết trình', category: 'Kỹ năng', unit: 'Hội SVHS', date: '20/04/2026', participants: 310, evidence: 16, status: 'approved' },
];

export const EVIDENCE_LIBRARY_DISPLAY_DATA = [
  { id: 1, name: 'Lễ khai mạc Ngày hội tình nguyện 2026', type: 'image', thumbnail: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=300&fit=crop', activity: 'Ngày hội tình nguyện mùa hè xanh 2026', uploadDate: '15/05/2026', size: '2.4 MB' },
  { id: 2, name: 'Video tổng hợp hoạt động tháng 5', type: 'video', activity: 'Chiến dịch Mùa hè xanh 2026', uploadDate: '14/05/2026', size: '45.2 MB' },
  { id: 3, name: 'Báo cáo kết quả Hội thảo khoa học', type: 'pdf', activity: 'Hội thảo khoa học sinh viên lần thứ 20', uploadDate: '12/05/2026', size: '1.8 MB' },
  { id: 4, name: 'Danh sách tham gia Workshop AI', type: 'excel', activity: 'Workshop về AI và Machine Learning', uploadDate: '10/05/2026', size: '156 KB' },
  { id: 5, name: 'Kế hoạch tổ chức hiến máu tình nguyện', type: 'word', activity: 'Hiến máu tình nguyện - Giọt hồng yêu thương', uploadDate: '08/05/2026', size: '420 KB' },
  { id: 6, name: 'Bài viết Facebook - Ngày hội tình nguyện', type: 'link', activity: 'Ngày hội tình nguyện mùa hè xanh 2026', uploadDate: '16/05/2026', url: 'https://facebook.com/...' },
  { id: 7, name: 'Thư viện ảnh hoạt động tháng 5', type: 'drive', activity: 'Tổng hợp minh chứng tháng 5/2026', uploadDate: '01/06/2026', url: 'https://drive.google.com/...' },
  { id: 8, name: 'Sinh viên tham gia tình nguyện', type: 'image', thumbnail: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop', activity: 'Chiến dịch Mùa hè xanh 2026', uploadDate: '13/05/2026', size: '3.1 MB' },
  { id: 9, name: 'Buổi tọa đàm với diễn giả', type: 'image', thumbnail: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400&h=300&fit=crop', activity: 'Talkshow kỹ năng giao tiếp', uploadDate: '11/05/2026', size: '2.7 MB' },
  { id: 10, name: 'Biên bản họp tổ chức SV5T', type: 'pdf', activity: 'Sinh viên 5 tốt cấp trường 2026', uploadDate: '09/05/2026', size: '890 KB' },
  { id: 11, name: 'Clip highlight ngày hội', type: 'video', activity: 'Ngày hội tình nguyện mùa hè xanh 2026', uploadDate: '17/05/2026', size: '128 MB' },
  { id: 12, name: 'Chứng nhận tham gia Olympic', type: 'image', thumbnail: 'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=400&h=300&fit=crop', activity: 'Cuộc thi Olympic Tin học sinh viên', uploadDate: '06/05/2026', size: '1.2 MB' },
];

export const UNIT_DIRECTORY_DISPLAY_DATA = [
  { id: 1, name: 'Đoàn CNTT', type: 'Đoàn khoa', level: 'Cấp Khoa', manager: 'Nguyễn Văn A', email: 'doan.cntt@university.edu.vn', activities: 85, status: 'active' },
  { id: 2, name: 'Hội Sinh viên Khoa học', type: 'Liên chi Hội', level: 'Cấp Khoa', manager: 'Trần Thị B', email: 'hoi.khoahoc@university.edu.vn', activities: 72, status: 'active' },
  { id: 3, name: 'Chi đoàn K66 CNTT', type: 'Chi đoàn', level: 'Cấp Lớp', manager: 'Lê Văn C', email: 'chidoan.k66cntt@university.edu.vn', activities: 28, status: 'active' },
  { id: 4, name: 'Chi hội SV Khoa học K67', type: 'Chi hội', level: 'Cấp Lớp', manager: 'Phạm Thị D', email: 'chihoi.k67kh@university.edu.vn', activities: 24, status: 'active' },
  { id: 5, name: 'CLB Lập trình AI', type: 'Câu lạc bộ', level: 'Cấp Trường', manager: 'Hoàng Văn E', email: 'clb.ai@university.edu.vn', activities: 32, status: 'active' },
  { id: 6, name: 'Đội tình nguyện Mùa hè xanh', type: 'Đội / Nhóm', level: 'Cấp Khoa', manager: 'Đỗ Thị F', email: 'doi.muahexanh@university.edu.vn', activities: 18, status: 'active' },
  { id: 7, name: 'Chi đoàn K65 Kinh tế', type: 'Chi đoàn', level: 'Cấp Lớp', manager: 'Vũ Văn G', email: 'chidoan.k65kt@university.edu.vn', activities: 15, status: 'inactive' },
  { id: 8, name: 'CLB Nhiếp ảnh', type: 'Câu lạc bộ', level: 'Cấp Trường', manager: 'Bùi Thị H', email: 'clb.nhiephanh@university.edu.vn', activities: 22, status: 'active' },
  { id: 9, name: 'Hội chữ thập đỏ Trường', type: 'Liên chi Hội', level: 'Cấp Trường', manager: 'Ngô Văn I', email: 'hoi.chuthapdo@university.edu.vn', activities: 54, status: 'active' },
  { id: 10, name: 'Chi hội SV K66 CNTT', type: 'Chi hội', level: 'Cấp Lớp', manager: 'Đinh Thị K', email: 'chihoi.k66cntt@university.edu.vn', activities: 26, status: 'active' },
];

export const APPROVAL_DISPLAY_DATA = [
  {
    id: 1,
    name: 'Ngày hội tình nguyện mùa hè xanh 2026',
    unit: 'Đoàn CNTT',
    submitDate: '15/05/2026',
    category: 'Tình nguyện',
    evidenceCount: 25,
    status: 'pending',
    level: 'Cấp Trường',
    startDate: '20/06/2026 08:00',
    endDate: '20/06/2026 17:00',
    location: 'Hội trường A',
    participants: 450,
    objective: 'Tổ chức ngày hội tình nguyện nhằm nâng cao ý thức trách nhiệm của sinh viên đối với cộng đồng.',
    content: 'Chương trình bao gồm: Lễ phát động, Workshop kỹ năng tình nguyện, Triển lãm ảnh, Trao giải cuộc thi.',
    evidences: { images: 45, files: 5, links: ['Facebook: Ngày hội tình nguyện', 'Google Drive: Thư viện ảnh'] },
    history: [{ date: '14/05/2026 10:00', action: 'Gửi yêu cầu duyệt', by: 'Nguyễn Văn A' }],
  },
  {
    id: 2,
    name: 'Hội thảo khoa học sinh viên lần thứ 20',
    unit: 'Đoàn Khoa học',
    submitDate: '12/05/2026',
    category: 'Học thuật',
    evidenceCount: 18,
    status: 'pending',
    level: 'Cấp Trường',
    startDate: '25/06/2026 08:00',
    endDate: '25/06/2026 17:00',
    location: 'Giảng đường B',
    participants: 320,
    objective: 'Tạo diễn đàn trao đổi học thuật cho sinh viên nghiên cứu khoa học.',
    content: 'Báo cáo các đề tài nghiên cứu, Trao giải các công trình xuất sắc, Giao lưu với chuyên gia.',
    evidences: { images: 30, files: 8, links: ['Facebook: Hội thảo KHSV', 'Drive: Tài liệu báo cáo'] },
    history: [{ date: '11/05/2026 14:00', action: 'Gửi yêu cầu duyệt', by: 'Trần Thị B' }],
  },
  {
    id: 3,
    name: 'Workshop về AI và Machine Learning',
    unit: 'Đoàn CNTT',
    submitDate: '01/05/2026',
    category: 'Học thuật',
    evidenceCount: 10,
    status: 'approved',
    level: 'Đoàn khoa',
    startDate: '15/05/2026 14:00',
    endDate: '15/05/2026 17:00',
    location: 'Phòng Lab 301',
    participants: 220,
    objective: 'Giới thiệu kiến thức cơ bản về AI và ML cho sinh viên.',
    content: 'Bài giảng lý thuyết, Thực hành coding, Q&A với diễn giả.',
    evidences: { images: 20, files: 3, links: ['Facebook: Workshop AI'] },
    history: [
      { date: '02/05/2026 09:00', action: 'Đã duyệt hoạt động', by: 'Admin', comment: 'Hoạt động tổ chức tốt, minh chứng đầy đủ.' },
      { date: '30/04/2026 16:00', action: 'Gửi yêu cầu duyệt', by: 'Lê Văn C' },
    ],
  },
  {
    id: 4,
    name: 'Cuộc thi Olympic Tin học sinh viên',
    unit: 'Đoàn CNTT',
    submitDate: '28/04/2026',
    category: 'Học thuật',
    evidenceCount: 12,
    status: 'need-update',
    level: 'Cấp Trường',
    startDate: '10/05/2026 08:00',
    endDate: '10/05/2026 17:00',
    location: 'Phòng máy A1, A2',
    participants: 180,
    objective: 'Tổ chức cuộc thi lập trình cho sinh viên.',
    content: 'Vòng loại online, Vòng chung kết onsite, Trao giải.',
    evidences: { images: 15, files: 4, links: ['Facebook: Olympic Tin học'] },
    history: [
      { date: '29/04/2026 10:00', action: 'Yêu cầu bổ sung', by: 'Admin', comment: 'Cần bổ sung danh sách thí sinh và kết quả thi.' },
      { date: '27/04/2026 15:00', action: 'Gửi yêu cầu duyệt', by: 'Phạm Thị D' },
    ],
  },
];

export const CALENDAR_DISPLAY_DATA = {
  days: [
    { date: 29, isCurrentMonth: false, activities: [] },
    { date: 30, isCurrentMonth: false, activities: [] },
    { date: 31, isCurrentMonth: false, activities: [] },
    { date: 1, isCurrentMonth: true, activities: [] },
    { date: 2, isCurrentMonth: true, activities: [] },
    { date: 3, isCurrentMonth: true, activities: [{ id: 1, title: 'Workshop AI', type: 'hoc-thuat', time: '14:00' }] },
    { date: 4, isCurrentMonth: true, activities: [] },
    { date: 5, isCurrentMonth: true, activities: [{ id: 2, title: 'Hiến máu tình nguyện', type: 'tinh-nguyen', time: '08:00' }] },
    { date: 6, isCurrentMonth: true, activities: [] },
    { date: 7, isCurrentMonth: true, activities: [] },
    { date: 8, isCurrentMonth: true, activities: [{ id: 3, title: 'Talkshow kỹ năng', type: 'ky-nang', time: '15:00' }] },
    { date: 9, isCurrentMonth: true, activities: [] },
    { date: 10, isCurrentMonth: true, activities: [{ id: 4, title: 'Hội thảo KHSV', type: 'hoc-thuat', time: '08:00' }] },
    { date: 11, isCurrentMonth: true, activities: [] },
    { date: 12, isCurrentMonth: true, activities: [] },
    { date: 13, isCurrentMonth: true, activities: [] },
    { date: 14, isCurrentMonth: true, activities: [] },
    { date: 15, isCurrentMonth: true, activities: [{ id: 5, title: 'SV5T cấp trường', type: 'sv5t', time: '09:00' }, { id: 6, title: 'Giải bóng đá', type: 'van-hoa', time: '16:00' }] },
    { date: 16, isCurrentMonth: true, activities: [] },
    { date: 17, isCurrentMonth: true, activities: [] },
    { date: 18, isCurrentMonth: true, activities: [{ id: 7, title: 'Ngày hội tình nguyện', type: 'tinh-nguyen', time: '08:00' }] },
    { date: 19, isCurrentMonth: true, activities: [] },
    { date: 20, isCurrentMonth: true, activities: [{ id: 8, title: 'Tuyên truyền chiến dịch', type: 'truyen-thong', time: '14:00' }] },
    { date: 21, isCurrentMonth: true, activities: [] },
    { date: 22, isCurrentMonth: true, activities: [] },
    { date: 23, isCurrentMonth: true, activities: [] },
    { date: 24, isCurrentMonth: true, activities: [] },
    { date: 25, isCurrentMonth: true, activities: [{ id: 9, title: 'Olympic Tin học', type: 'hoc-thuat', time: '08:00' }] },
    { date: 26, isCurrentMonth: true, activities: [] },
    { date: 27, isCurrentMonth: true, activities: [] },
    { date: 28, isCurrentMonth: true, activities: [{ id: 10, title: 'Ngày hội văn hóa', type: 'van-hoa', time: '09:00' }] },
    { date: 29, isCurrentMonth: true, activities: [] },
    { date: 30, isCurrentMonth: true, activities: [] },
    { date: 31, isCurrentMonth: true, activities: [] },
    { date: 1, isCurrentMonth: false, activities: [] },
    { date: 2, isCurrentMonth: false, activities: [] },
  ],
  upcomingActivities: [
    { id: 11, title: 'Workshop về AI và Machine Learning', type: 'Học thuật', date: '15/06/2026', time: '14:00 - 17:00', location: 'Phòng Lab 301', unit: 'Đoàn CNTT' },
    { id: 12, title: 'Ngày hội tình nguyện mùa hè xanh', type: 'Tình nguyện', date: '20/06/2026', time: '08:00 - 17:00', location: 'Hội trường A', unit: 'Đoàn CNTT' },
    { id: 13, title: 'Talkshow kỹ năng giao tiếp', type: 'Kỹ năng', date: '22/06/2026', time: '15:00 - 17:00', location: 'Giảng đường B', unit: 'Hội SVHS' },
    { id: 14, title: 'Sinh viên 5 tốt cấp trường 2026', type: 'SV5T', date: '25/06/2026', time: '09:00 - 12:00', location: 'Hội trường lớn', unit: 'Hội SVHS' },
    { id: 15, title: 'Giải bóng đá sinh viên', type: 'Văn hóa', date: '28/06/2026', time: '16:00 - 18:00', location: 'Sân vận động trường', unit: 'Hội SVHS' },
  ],
};

export const CONFIG_DISPLAY_DATA = {
  activityTypes: [
    { id: 1, name: 'Học thuật', color: '#3b82f6', count: 120 },
    { id: 2, name: 'Tình nguyện', color: '#10b981', count: 95 },
    { id: 3, name: 'Kỹ năng', color: '#8b5cf6', count: 80 },
    { id: 4, name: 'SV5T', color: '#f59e0b', count: 65 },
    { id: 5, name: 'Truyền thông', color: '#06b6d4', count: 50 },
    { id: 6, name: 'Văn hóa - Thể thao', color: '#ec4899', count: 45 },
  ],
  statuses: [
    { id: 'draft', name: 'Nháp', color: '#6b7280', enabled: true },
    { id: 'pending', name: 'Chờ duyệt', color: '#f59e0b', enabled: true },
    { id: 'approved', name: 'Đã duyệt', color: '#10b981', enabled: true },
    { id: 'need-update', name: 'Cần bổ sung', color: '#f97316', enabled: true },
    { id: 'rejected', name: 'Từ chối', color: '#ef4444', enabled: true },
  ],
  reportTemplates: [
    { id: 'yearly', name: 'Báo cáo tổng hợp năm học', description: 'Tổng hợp toàn bộ hoạt động trong năm học' },
    { id: 'topic', name: 'Báo cáo hoạt động theo chuyên đề', description: 'Báo cáo chi tiết theo từng loại hoạt động' },
    { id: 'competition', name: 'Báo cáo thi đua', description: 'Dành cho báo cáo thi đua cấp trên' },
    { id: 'evidence', name: 'Báo cáo minh chứng', description: 'Tập hợp minh chứng hoạt động' },
    { id: 'sv5t', name: 'Báo cáo Sinh viên 5 tốt', description: 'Báo cáo cho phong trào SV5T' },
  ],
};

export const ARCHIVE_DISPLAY_DATA = [
  { id: 1, name: '2025-2026', startDate: '01/09/2025', endDate: '31/08/2026', activities: 245, evidence: 1850, reports: 45, size: '3.2 GB', status: 'active' },
  { id: 2, name: '2024-2025', startDate: '01/09/2024', endDate: '31/08/2025', activities: 238, evidence: 1720, reports: 42, size: '2.8 GB', status: 'locked' },
  { id: 3, name: '2023-2024', startDate: '01/09/2023', endDate: '31/08/2024', activities: 225, evidence: 1650, reports: 38, size: '2.5 GB', status: 'archived-ready' },
  { id: 4, name: '2022-2023', startDate: '01/09/2022', endDate: '31/08/2023', activities: 210, evidence: 1580, reports: 35, size: '2.3 GB', status: 'archived' },
  { id: 5, name: '2021-2022', startDate: '01/09/2021', endDate: '31/08/2022', activities: 195, evidence: 1420, reports: 32, size: '2.1 GB', status: 'deleted-online' },
];

export const UNIT_RANKING_DISPLAY_DATA = [
  { rank: 1, name: 'Đoàn CNTT', activities: 85, participants: 3250, change: 12 },
  { rank: 2, name: 'Hội SVHS', activities: 72, participants: 2890, change: 8 },
  { rank: 3, name: 'Đoàn Khoa học', activities: 68, participants: 2640, change: 15 },
  { rank: 4, name: 'Hội chữ thập đỏ', activities: 54, participants: 2180, change: 5 },
  { rank: 5, name: 'Đoàn Kinh tế', activities: 48, participants: 1920, change: -3 },
];

export const ACTIVITY_DETAIL_DISPLAY_DATA = {
  id: 1,
  title: 'Ngày hội tình nguyện mùa hè xanh 2026',
  category: 'Tình nguyện',
  unit: 'Đoàn CNTT',
  status: 'approved',
  image: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=1200&h=400&fit=crop',
  startDate: '20/06/2026 08:00',
  endDate: '20/06/2026 17:00',
  location: 'Hội trường A - Trường Đại học ABC',
  level: 'Cấp Trường',
  target: 'Sinh viên K66, K67',
  participants: 450,
  objective: 'Tổ chức ngày hội tình nguyện nhằm nâng cao ý thức trách nhiệm của sinh viên đối với cộng đồng, góp phần lan tỏa tinh thần tình nguyện và những giá trị nhân văn trong môi trường sinh viên.',
  content: 'Chương trình bao gồm các hoạt động: Lễ phát động chiến dịch tình nguyện, Workshop về kỹ năng tình nguyện, Triển lãm ảnh các hoạt động tình nguyện tiêu biểu, Trao giải cuộc thi sáng tạo về tình nguyện, Giao lưu với các tình nguyện viên xuất sắc.',
  result: 'Chương trình thu hút 450 sinh viên tham gia, trong đó có 120 sinh viên đăng ký trở thành tình nguyện viên chính thức. Đã trao 30 giải thưởng cho các dự án tình nguyện xuất sắc. Thu thập được 5 tấn quần áo và 200 quyển sách ủng hộ cho vùng khó khăn.',
  note: 'Hoạt động được phối hợp với Hội chữ thập đỏ và các đơn vị tình nguyện địa phương.',
  fbLink: 'https://facebook.com/doan.cntt/posts/123456',
  driveLink: 'https://drive.google.com/drive/folders/abc123',
  creator: { name: 'Nguyễn Văn A', role: 'Bí thư Đoàn CNTT', avatar: '' },
  history: [
    { date: '15/06/2026 14:30', action: 'Đã duyệt hoạt động', by: 'Admin' },
    { date: '14/06/2026 10:00', action: 'Gửi yêu cầu duyệt', by: 'Nguyễn Văn A' },
    { date: '10/06/2026 09:00', action: 'Tạo hoạt động', by: 'Nguyễn Văn A' },
  ],
  images: [
    'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=300&fit=crop',
    'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop',
    'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400&h=300&fit=crop',
    'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=400&h=300&fit=crop',
    'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400&h=300&fit=crop',
    'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=300&fit=crop',
  ],
};

export const DASHBOARD_CHART_DISPLAY_DATA = {
  statsByYear: {
    2026: { totalActivities: 410, monthlyActivities: 73, participants: 8450, evidence: 2340, pending: 28, monthlyChange: '+12%' },
    2025: { totalActivities: 385, monthlyActivities: 68, participants: 7920, evidence: 2180, pending: 15, monthlyChange: '+8%' },
    2024: { totalActivities: 358, monthlyActivities: 62, participants: 7340, evidence: 1950, pending: 12, monthlyChange: '+15%' },
    2023: { totalActivities: 325, monthlyActivities: 58, participants: 6850, evidence: 1720, pending: 10, monthlyChange: '+10%' },
    2022: { totalActivities: 298, monthlyActivities: 52, participants: 6200, evidence: 1580, pending: 8, monthlyChange: '+5%' },
  },
  recentActivities: [
    { id: 1, name: 'Ngày hội tình nguyện mùa hè xanh 2026', unit: 'Đoàn CNTT', time: '15/05/2026', status: 'approved', statusText: 'Đã duyệt' },
    { id: 2, name: 'Hội thảo khoa học sinh viên lần thứ 20', unit: 'Đoàn Khoa học', time: '12/05/2026', status: 'pending', statusText: 'Chờ duyệt' },
    { id: 3, name: 'Chương trình đào tạo kỹ năng mềm K66', unit: 'Hội SVHS', time: '10/05/2026', status: 'approved', statusText: 'Đã duyệt' },
    { id: 4, name: 'Hiến máu tình nguyện - Giọt hồng yêu thương', unit: 'Hội chữ thập đỏ', time: '08/05/2026', status: 'completed', statusText: 'Hoàn thành' },
    { id: 5, name: 'Cuộc thi Olympic Tin học sinh viên', unit: 'Đoàn CNTT', time: '05/05/2026', status: 'approved', statusText: 'Đã duyệt' },
  ],
  dashboardFeatured: [
    { id: 1, title: 'Ngày hội tình nguyện', date: '20/06/2026', participants: 450, location: 'Hội trường A', image: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=250&fit=crop' },
    { id: 2, title: 'Hội thảo khởi nghiệp', date: '25/06/2026', participants: 320, location: 'Giảng đường B', image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=250&fit=crop' },
    { id: 3, title: 'Chương trình đào tạo', date: '30/06/2026', participants: 280, location: 'Phòng 301', image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400&h=250&fit=crop' },
  ],
  monthlyActivities: [
    { id: 'm1', month: 'T1', activities: 45 },
    { id: 'm2', month: 'T2', activities: 52 },
    { id: 'm3', month: 'T3', activities: 61 },
    { id: 'm4', month: 'T4', activities: 48 },
    { id: 'm5', month: 'T5', activities: 70 },
    { id: 'm6', month: 'T6', activities: 55 },
    { id: 'm7', month: 'T7', activities: 42 },
    { id: 'm8', month: 'T8', activities: 65 },
    { id: 'm9', month: 'T9', activities: 58 },
    { id: 'm10', month: 'T10', activities: 73 },
    { id: 'm11', month: 'T11', activities: 68 },
    { id: 'm12', month: 'T12', activities: 80 },
  ],
  categoryStats: [
    { id: 'cat1', name: 'Học thuật', value: 120, color: '#3b82f6' },
    { id: 'cat2', name: 'Tình nguyện', value: 95, color: '#0ea5e9' },
    { id: 'cat3', name: 'Kỹ năng', value: 80, color: '#06b6d4' },
    { id: 'cat4', name: 'SV5T', value: 65, color: '#22d3ee' },
    { id: 'cat5', name: 'Truyền thông', value: 50, color: '#67e8f9' },
  ],
  participantTrend: [
    { month: 'T1', participants: 1200 },
    { month: 'T2', participants: 1450 },
    { month: 'T3', participants: 1680 },
    { month: 'T4', participants: 1520 },
    { month: 'T5', participants: 2100 },
    { month: 'T6', participants: 1850 },
  ],
};

export const REPORT_TEMPLATE_CONFIG_DISPLAY_DATA = {
  reportTypes: ['Kết quả hoạt động', 'Tổng kết năm học', 'Thi đua', 'Minh chứng', 'Sinh viên 5 tốt', 'Mô hình, giải pháp', 'Hoạt động chuyên đề'],
  units: ['Toàn hệ thống', 'Đoàn khoa', 'Liên chi Hội khoa', 'Chi đoàn', 'Chi hội', 'Câu lạc bộ'],
  templates: [
    { id: 1, name: 'Báo cáo kết quả hoạt động', type: 'Kết quả hoạt động', unit: 'Toàn hệ thống', fields: 12, formats: ['Word', 'PDF', 'Excel'], isDefault: true, status: 'active', updatedAt: '15/05/2026' },
    { id: 2, name: 'Báo cáo tổng kết năm học', type: 'Tổng kết năm học', unit: 'Đoàn khoa', fields: 15, formats: ['Word', 'PDF'], isDefault: false, status: 'active', updatedAt: '12/05/2026' },
    { id: 3, name: 'Báo cáo thi đua Đoàn - Hội', type: 'Thi đua', unit: 'Toàn hệ thống', fields: 10, formats: ['Word', 'PDF', 'Excel'], isDefault: false, status: 'active', updatedAt: '10/05/2026' },
    { id: 4, name: 'Báo cáo minh chứng hoạt động', type: 'Minh chứng', unit: 'Chi đoàn', fields: 8, formats: ['PDF', 'Excel'], isDefault: false, status: 'active', updatedAt: '08/05/2026' },
    { id: 5, name: 'Báo cáo hoạt động tình nguyện', type: 'Hoạt động chuyên đề', unit: 'Toàn hệ thống', fields: 11, formats: ['Word', 'PDF'], isDefault: false, status: 'draft', updatedAt: '05/05/2026' },
    { id: 6, name: 'Báo cáo hoạt động học thuật', type: 'Hoạt động chuyên đề', unit: 'Đoàn khoa', fields: 9, formats: ['Word', 'PDF'], isDefault: false, status: 'active', updatedAt: '03/05/2026' },
    { id: 7, name: 'Báo cáo Sinh viên 5 tốt', type: 'Sinh viên 5 tốt', unit: 'Toàn hệ thống', fields: 14, formats: ['Word', 'PDF', 'Excel'], isDefault: false, status: 'active', updatedAt: '01/05/2026' },
    { id: 8, name: 'Báo cáo mô hình, giải pháp', type: 'Mô hình, giải pháp', unit: 'Liên chi Hội khoa', fields: 13, formats: ['Word', 'PDF'], isDefault: false, status: 'locked', updatedAt: '28/04/2026' },
  ],
  dataFields: ['{{ten_hoat_dong}}', '{{loai_hoat_dong}}', '{{don_vi_to_chuc}}', '{{thoi_gian}}', '{{dia_diem}}', '{{so_luong_tham_gia}}', '{{noi_dung_hoat_dong}}', '{{ket_qua_dat_duoc}}', '{{link_minh_chung}}', '{{hinh_anh_minh_chung}}', '{{nguoi_phu_trach}}', '{{ngay_tao_bao_cao}}'],
  templateStructure: ['I. Thông tin chung', 'II. Mục đích, yêu cầu', 'III. Nội dung triển khai', 'IV. Kết quả thực hiện', 'V. Số liệu tham gia', 'VI. Minh chứng kèm theo', 'VII. Đánh giá, kiến nghị'],
};

export const INTERFACE_DISPLAY_SEED_DOCS = [
  { id: 'danh_sach_hoat_dong', data: { items: ACTIVITY_LIST_DISPLAY_DATA } },
  { id: 'kho_minh_chung', data: { items: EVIDENCE_LIBRARY_DISPLAY_DATA } },
  { id: 'danh_sach_don_vi', data: { items: UNIT_DIRECTORY_DISPLAY_DATA } },
  { id: 'duyet_hoat_dong', data: { items: APPROVAL_DISPLAY_DATA } },
  { id: 'lich_hoat_dong', data: CALENDAR_DISPLAY_DATA },
  { id: 'cau_hinh_giao_dien', data: CONFIG_DISPLAY_DATA },
  { id: 'luu_tru_nam_hoc', data: { items: ARCHIVE_DISPLAY_DATA } },
  { id: 'bang_xep_hang_don_vi', data: { items: UNIT_RANKING_DISPLAY_DATA } },
  { id: 'chi_tiet_hoat_dong_mac_dinh', data: ACTIVITY_DETAIL_DISPLAY_DATA },
  { id: 'du_lieu_bieu_do_dashboard', data: DASHBOARD_CHART_DISPLAY_DATA },
  { id: 'cau_hinh_mau_bao_cao', data: REPORT_TEMPLATE_CONFIG_DISPLAY_DATA },
];
